name: uber_users_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # ✅ Firebase Core + Services  
  firebase_core: ^2.27.2
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.7.7
  firebase_database: ^10.0.7
  permission_handler: ^10.2.0
  googleapis_auth: ^2.0.0

  # ✅ Authentication
  google_sign_in: ^6.2.1
  country_picker: ^2.0.20
  pinput: ^5.0.0

  # ✅ State Management
  provider: ^6.1.2

  # ✅ Location + Maps
  google_maps_flutter_web: ^0.5.6+2
  google_maps_flutter: ^2.6.1
  geolocator: ^10.1.0
  flutter_geofire: ^2.0.3
  flutter_polyline_points: ^3.0.1

  # ✅ Connectivity
  connectivity_plus: ^5.0.2

  # ✅ Stripe (for payments)
  flutter_stripe: ^10.2.0

  # ✅ Utilities
  http: ^1.2.0
  url_launcher: ^6.2.5
  restart_app: ^1.2.1
  loading_animation_widget: ^1.2.0+4

  # ✅ Cupertino icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - themes/
    - assets/vehicles/
